server:
  port: 8089

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_status?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 # HikariCP 유효성 검사 추가
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # 오직 테스트 환경에서만
      generate-ddl: true # 오직 테스트 환경에서만
      show-sql: true
    open-in-view: false
#  kafka:
#    bootstrap-servers: localhost:9092
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
